# Build Pipeline for Suil Project
image: alpine:latest

variables:
  SUIL_BUILD_VERSION: $SUIL_MAJOR_VERSION.$SUIL_PATCH_VERSION.$SUIL_MINOR_VERSION-$SUIL_VERSION_TAG

build:dev:
  stage: build
  tags:
    - alpine
  only:
    - master
  # Install all the required dependencies before proceeding to build
  before_script: 
    - apk update
    - apk add openssl docker
    - docker login -u "$SUIL_REGISTRY_USER" -p "$SUIL_REGISTRY_PASSWD" "$CI_REGISTRY"
    - apk add openssh bash cmake sqlite sqlite-dev
    - apk add libressl-dev postgresql-dev
    - apk add bsd-compat-headers gcc g++ make util-linux-dev
    
  script:
    - mkdir -p ./build$CI_COMMIT_TAG
    - cd ./build$CI_COMMIT_TAG
    - cmake ..
       -DSUIL_MAJOR_VERSION=$SUIL_MAJOR_VERSION
       -DSUIL_MINOR_VERSION=$SUIL_MINOR_VERSION 
       -DSUIL_PATCH_VERSION=$SUIL_PATCH_VERSION 
       -DSUIL_BUILD_NUMBER=$CI_JOB_ID
       -DSUIL_BUILD_DEV_PACKAGE=ON
    - make clean
    - make -j2 install
    - cp -r ../Dockerfile.build.alpine ./Dockerfile
    - docker build --pull -t "production/$CI_REGISTRY_IMAGE:latest" .
    - docker push "production/$CI_REGISTRY_IMAGE:latest"
    - cd ..

  cache:
    paths:
      - ./build$CI_COMMIT_TAG/
  artifacts:
    paths:
      - ./build$CI_COMMIT_TAG/sut
    expire_in: 30 mins

build:release:prod:
  stage: build
  tags:
    - alpine
  only:
    - tags
# Install all the required dependencies before proceeding to build
  before_script: 
    - apk update
    - apk add openssl docker
    - docker login -u "$SUIL_REGISTRY_USER" -p "$SUIL_REGISTRY_PASSWD" "$CI_REGISTRY"
    - apk add openssh bash cmake sqlite sqlite-dev
    - apk add libressl-dev postgresql-dev
    - apk add bsd-compat-headers gcc g++ make util-linux-dev
    
  script:
    - mkdir -p ./build$CI_COMMIT_TAG
    - cd ./build$CI_COMMIT_TAG
    - rm -rf *.tag.gz
    # Build runtime binaries
    - cmake ..
       -DSUIL_MAJOR_VERSION=$SUIL_MAJOR_VERSION 
       -DSUIL_MINOR_VERSION=$SUIL_MINOR_VERSION 
       -DSUIL_PATCH_VERSION=$SUIL_PATCH_VERSION
       -DSUIL_BUILD_TAG=$SUIL_VERSION_TAG
       -DSUIL_BUILD_NUMBER=$CI_JOB_ID
       -DSUIL_BUILD_DEV_PACKAGE=OFF
    - make clean
    - make -j2 install package
    - cp -r ../Dockerfile.alpine ./Dockerfile
    - docker build --pull -t "production/$CI_REGISTRY_IMAGE:$SUIL_BUILD_VERSION" .
    - docker push "production/$CI_REGISTRY_IMAGE:$SUIL_BUILD_VERSION"
    - cd ..

  artifacts:
    paths:
      - ./build$CI_COMMIT_TAG/sut
      - ./build$CI_COMMIT_TAG/suil*tar.gz

build:release:devel:
  stage: build
  tags:
    - alpine
  only:
    - tags
# Install all the required dependencies before proceeding to build
  before_script:
    - apk update
    - apk add openssl docker
    - docker login -u "$SUIL_REGISTRY_USER" -p "$SUIL_REGISTRY_PASSWD" "$CI_REGISTRY"
    - apk add openssh bash cmake sqlite sqlite-dev
    - apk add libressl-dev postgresql-dev
    - apk add bsd-compat-headers gcc g++ make util-linux-dev

  script:
    # Build development binaries
    - mkdir -p ./build$CI_COMMIT_TAG
    - cd ./build$CI_COMMIT_TAG
    - rm -rf *.tag.gz
    - cmake ..
       -DSUIL_MAJOR_VERSION=$SUIL_MAJOR_VERSION 
       -DSUIL_MINOR_VERSION=$SUIL_MINOR_VERSION 
       -DSUIL_PATCH_VERSION=$SUIL_PATCH_VERSION
       -DSUIL_BUILD_TAG=$SUIL_VERSION_TAG
       -DSUIL_BUILD_NUMBER=$CI_JOB_ID
       -DSUIL_BUILD_DEV_PACKAGE=ON
    - make clean
    - make -j2 package
    - cp -r ../Dockerfile.alpine ./Dockerfile
    - docker build --pull -t "development/$CI_REGISTRY_IMAGE:$SUIL_BUILD_VERSION" .
    - docker push "development/$CI_REGISTRY_IMAGE:$SUIL_BUILD_VERSION"
    - cd ..

  artifacts:
    paths:
      - ./build$CI_COMMIT_TAG/sut
      - ./build$CI_COMMIT_TAG/suil*tar.gz
      
test:
  stage: test
  tags:
    - alpine
  before_script:
    - apk update
    - apk add openssl libressl postgresql
    - apk add sqlite musl libstdc++ libuuid
  script:
    - cd ./build$CI_COMMIT_TAG
    - ./sut