# Build Pipeline for Suil Project
image: alpine:latest

build:
  stage: build
  tags:
    - alpine
  # Install all the required dependecies before proceeding to build
  before_script: 
    - apk update
    - apk add openssh bash cmake sqlite sqlite-dev
    - apk add openssl libressl-dev postgresql-dev
    - apk add bsd-compat-headers gcc g++ make
    
  script:
    - mkdir -p ./build
    - cd ./build
    - cmake ..
    - make clean
    - make -j2 package -DSUIL_MAJOR_VERSION=$SUIL_MAJOR_VERSION \
       -DSUIL_MINOR_VERSION=$SUIL_MINOR_VERSION \
       -DSUIL_PATCH_VERSION=$SUIL_PATCH_VERSION \
       -DSUIL_BUILD_NUMBER=$CI_JOB_ID
       
    - cd ..
  cache:
    paths:
      - build/sut
      - build/suil*tar.deb
  artifacts:
    paths:
      - build/suil*tar.gz