# Build Pipeline for Suil Project
image: alpine:latest

build:
  stage: build
  tags:
    - alpine
  # Install all the required dependecies before proceeding to build
  before_script: 
    - apk update
    - apk add openssh bash cmake sqlite sqlite-dev openssl openssl-dev
    - apk add bsd-compat-headers add gcc g++ make
    
  script:
    - mkdir -p ./build
    - cd ./build
    - cmake ..
    - make clean && make -j2 package
    - cd ..
  cache:
    paths:
      - build/sut
      - build/suil*tar.deb
  artifacts:
    paths:
      - build/suil*tar.gz