# This file is a template, and might need editing before it works on your project.
# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
image: alpine:latest

build:
  stage: build
  tags:
    - build02
  # Install all the required dependecies before proceeding to build
  before_script: 
    - apk update
    - apk add openssh bash cmake sqlite sqlite-dev openssl openssl-dev
    - apk add bsd-compat-headers
    - apk add gcc g++ make
    
  script:
    - mkdir -p ./build
    - cd ./build
    - cmake ..
    - make clean
    - make -j2
    - cd ..
  artifacts:
    paths:
      - build/sut
      - build/suil*tar.gz
      - build/suil*tar.deb