FROM alpine:latest
MAINTAINER "Carter Mbotho <carter@suilteam.com>"

# Install dependencies
RUN apk update
RUN apk  add libressl postgresql libressl2.6-libcrypto && \
         apk add sqlite musl libstdc++ libuuid

# Copy Binaries
COPY artifacts/ /usr/local/
COPY sut        /usr/local/bin/sut