FROM alpine:latest
MAINTAINER "Carter Mbotho <carter@suilteam.com>"

# Install dependencies
RUN apk update
RUN apk  add openssl libressl postgresql && \
         apk add sqlite musl libstdc++ libuuid protobuf

# Copy Binaries
COPY artifacts/ /usr/local/
COPY sut        /usr/local/bin/sut